name: wine-platform-7-staging-core20
adopt-info: wine
summary: wine platform snap it provides staging WINE 7 for snaps
description: |
 This snap creates a WINE staging 7 via content sharing to be used by other snaps that are using WINE.

grade: stable
confinement: strict
architectures:
  - build-on: amd64
base: core20
compression: lzo

slots:
  wine-7-staging:
    interface: content
    source:
      read:
      - $SNAP/opt/wine-staging

parts:
  wine:
    plugin: nil
    build-packages:
      - dpkg
      - wget
    override-build: |
      snapcraftctl build

      WINE_VER="7.0-5"

      # set snap version
      snapcraftctl set-version "$WINE_VER"

      mkdir -p ${SNAPCRAFT_PART_INSTALL}/opt
      (cd ${SNAPCRAFT_PART_INSTALL}/opt ; wget -q wget -q "https://github.com/GloriousEggroll/wine-ge-custom/releases/download/7.0-GE-5-LoL/wine-lutris-ge-lol-7.0-5-x86_64.tar.xz" ; tar -xf *.tar.xz ; mv lutris* wine-staging ; rm *.tar.xz )
